# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 450)
        MainWindow.setMinimumSize(QtCore.QSize(800, 450))
        MainWindow.setMaximumSize(QtCore.QSize(800, 450))
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 90, 531, 271))
        self.tableWidget.setAlternatingRowColors(False)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 370, 171, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(100, 10, 551, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(580, 120, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(660, 160, 21, 16))
        self.label_4.setObjectName("label_4")
        self.idEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.idEdit.setGeometry(QtCore.QRect(680, 160, 113, 22))
        self.idEdit.setObjectName("idEdit")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(600, 200, 71, 16))
        self.label_5.setObjectName("label_5")
        self.serialNameEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.serialNameEdit.setGeometry(QtCore.QRect(680, 200, 113, 22))
        self.serialNameEdit.setObjectName("serialNameEdit")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(570, 240, 111, 16))
        self.label_6.setObjectName("label_6")
        self.numSeriesEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.numSeriesEdit.setGeometry(QtCore.QRect(680, 240, 113, 22))
        self.numSeriesEdit.setObjectName("numSeriesEdit")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(610, 280, 71, 16))
        self.label_7.setObjectName("label_7")
        self.isWatchedEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.isWatchedEdit.setGeometry(QtCore.QRect(680, 280, 113, 22))
        self.isWatchedEdit.setObjectName("isWatchedEdit")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(-3, 40, 811, 16))
        self.line.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.showButton = QtWidgets.QPushButton(self.centralwidget)
        self.showButton.setGeometry(QtCore.QRect(650, 330, 71, 31))
        self.showButton.setObjectName("showButton")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(470, 60, 321, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.searchButton = QtWidgets.QPushButton(self.centralwidget)
        self.searchButton.setGeometry(QtCore.QRect(700, 110, 81, 31))
        self.searchButton.setObjectName("searchButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setNativeMenuBar(True)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuDelete_record = QtWidgets.QMenu(self.menuEdit)
        self.menuDelete_record.setObjectName("menuDelete_record")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionClean = QtWidgets.QAction(MainWindow)
        self.actionClean.setObjectName("actionClean")
        self.actionDelete = QtWidgets.QAction(MainWindow)
        self.actionDelete.setObjectName("actionDelete")
        self.actionAddRecord = QtWidgets.QAction(MainWindow)
        self.actionAddRecord.setObjectName("actionAddRecord")
        self.actionChangeRecord = QtWidgets.QAction(MainWindow)
        self.actionChangeRecord.setObjectName("actionChangeRecord")
        self.actionDelete_by_key = QtWidgets.QAction(MainWindow)
        self.actionDelete_by_key.setObjectName("actionDelete_by_key")
        self.actionDelete_by_value = QtWidgets.QAction(MainWindow)
        self.actionDelete_by_value.setObjectName("actionDelete_by_value")
        self.actionBackup = QtWidgets.QAction(MainWindow)
        self.actionBackup.setObjectName("actionBackup")
        self.actionXlsx = QtWidgets.QAction(MainWindow)
        self.actionXlsx.setObjectName("actionXlsx")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClean)
        self.menuFile.addAction(self.actionDelete)
        self.menuDelete_record.addAction(self.actionDelete_by_key)
        self.menuDelete_record.addAction(self.actionDelete_by_value)
        self.menuEdit.addAction(self.actionAddRecord)
        self.menuEdit.addAction(self.actionChangeRecord)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.menuDelete_record.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.idEdit, self.serialNameEdit)
        MainWindow.setTabOrder(self.serialNameEdit, self.numSeriesEdit)
        MainWindow.setTabOrder(self.numSeriesEdit, self.isWatchedEdit)
        MainWindow.setTabOrder(self.isWatchedEdit, self.tableWidget)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "id"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "serial_name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "number_of_series"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "is_watched"))
        self.label.setText(_translate("MainWindow", "Creator: Prishchepa Kseniya"))
        self.label_2.setText(_translate("MainWindow", "Good afternoon! It is the fisrt homeproject: \"File Data Base\"!"))
        self.label_3.setText(_translate("MainWindow", "Searching by..."))
        self.label_4.setText(_translate("MainWindow", "id"))
        self.label_5.setText(_translate("MainWindow", "serial_name"))
        self.label_6.setText(_translate("MainWindow", "number_of_series"))
        self.label_7.setText(_translate("MainWindow", "is_watched"))
        self.showButton.setText(_translate("MainWindow", "Show"))
        self.label_8.setText(_translate("MainWindow", "You can choose only one field of searching!"))
        self.searchButton.setText(_translate("MainWindow", "Search"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuDelete_record.setTitle(_translate("MainWindow", "Delete record..."))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionOpen.setText(_translate("MainWindow", "Open ..."))
        self.actionSave.setText(_translate("MainWindow", "Save ..."))
        self.actionClean.setText(_translate("MainWindow", "Clean"))
        self.actionDelete.setText(_translate("MainWindow", "Delete"))
        self.actionAddRecord.setText(_translate("MainWindow", "Add record"))
        self.actionChangeRecord.setText(_translate("MainWindow", "Change record"))
        self.actionDelete_by_key.setText(_translate("MainWindow", "by key"))
        self.actionDelete_by_value.setText(_translate("MainWindow", "by value"))
        self.actionBackup.setText(_translate("MainWindow", "back-up file [.txt]"))
        self.actionXlsx.setText(_translate("MainWindow", "to [.xlsx] format"))
